# Generated by Django 4.2 on 2026-04-20 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_region', models.CharField(max_length=50)),
                ('recommended_region', models.CharField(max_length=50)),
                ('current_monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potential_monthly_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbon_profile_current', models.CharField(max_length=20)),
                ('carbon_profile_recommended', models.CharField(max_length=20)),
                ('latency_impact', models.CharField(default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_optimizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-potential_monthly_savings'],
            },
        ),
        migrations.CreateModel(
            name='IdleResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(max_length=20)),
                ('resource_id', models.CharField(max_length=200)),
                ('resource_name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('EC2', 'EC2 Instance'), ('RDS', 'RDS Database'), ('STORAGE', 'Storage'), ('NAT', 'NAT Gateway'), ('ELB', 'Load Balancer')], max_length=20)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idle_duration_days', models.IntegerField()),
                ('cpu_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('network_mbph', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_accessed', models.DateTimeField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_action', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-monthly_cost'],
            },
        ),
        migrations.CreateModel(
            name='CostSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rightsizing_percent', models.IntegerField(default=10)),
                ('reserved_savings_percent', models.IntegerField(default=18)),
                ('spot_instances_percent', models.IntegerField(default=0)),
                ('projected_monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('MONTHLY', 'Monthly Summary'), ('EXECUTIVE', 'Executive Summary'), ('DETAILED', 'Detailed Analysis'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_breakdown', models.JSONField(default=dict)),
                ('region_breakdown', models.JSONField(default=dict)),
                ('tag_breakdown', models.JSONField(default=dict)),
                ('recommendations_count', models.IntegerField(default=0)),
                ('anomalies_detected', models.IntegerField(default=0)),
                ('file_format', models.CharField(default='pdf', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=300)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_emails', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TagCostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(max_length=20)),
                ('tag_key', models.CharField(max_length=200)),
                ('tag_value', models.CharField(max_length=200)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resource_count', models.IntegerField()),
                ('services', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_cost_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_cost'],
                'unique_together': {('user', 'cloud_provider', 'tag_key', 'tag_value')},
            },
        ),
    ]
